#NTEAgathoklesBundle
agathokles_fiches:
    resource: "@NTEAgathoklesBundle/Controller/"
    type:     annotation
    prefix:   /

recherche:
    pattern: /recherche

fiche:
    pattern: /fiche/{id}

print:
    pattern: /print/{id}

home:
    pattern: /
