<?php

namespace NTE\AgathoklesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LieuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LieuRepository extends EntityRepository
{
}
